version: '3.8'

name: licest

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  api:
    build: ./api
    restart: always
    environment:
      API_PORT: "${API_PORT}"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public"
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db

volumes:
  db:
