version: '3.1'

services:
  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PORT: "${MYSQL_PORT}"
    expose:
      - "${MYSQL_PORT}"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"

  api:
    build: ./api
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PORT: "${MYSQL_PORT}"
      API_PORT: "${API_PORT}"
    ports:
      - "${API_PORT}:${API_PORT}"

  client:
    build: ./client
    depends_on:
      - api
    environment:
      REACT_APP_API_HOST: "${API_HOST}"
      REACT_APP_API_PORT: "${API_PORT}"
    ports:
      - "3000:3000"

volumes:
    db:
      driver: local
