version: '3.1'

services:
  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    expose:
      - "3306"
    ports:
      - "3306:3306"

  api:
    build: ./api
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "8080:8080"

  client:
    build: ./client
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
    db:
      driver: local
